/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_audio_jni_AudioPreprocessJni */

#ifndef _Included_com_audio_jni_AudioPreprocessJni
#define _Included_com_audio_jni_AudioPreprocessJni
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jboolean JNICALL Java_com_audio_jni_AudioPreprocessJni_preprocess
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
