/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soundeffect */

#ifndef _Included_com_soundeffect
#define _Included_com_soundeffect
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_audio_jni_SoundEffectJni_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
